CREATE TABLE tenants (
    id UUID PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    country VARCHAR(2) NOT NULL DEFAULT 'PT',
    currency VARCHAR(3) NOT NULL DEFAULT 'EUR',
    language VARCHAR(10) NOT NULL DEFAULT 'pt-PT',
    timezone VARCHAR(80) NOT NULL DEFAULT 'Europe/Lisbon',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);